{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mychart.name" . }} 
  labels:
    app.kubernetes.io/name: nginx-app
    app.kubernetes.io/instance: nginx
{{- end }}

