---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mychart.name" . }}
  labels:
    app.kubernetes.io/name: nginx-app
    app.kubernetes.io/instance: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-app
      app.kubernetes.io/instance: nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-app
        app.kubernetes.io/instance: nginx
    spec:
     {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ .Release.Name }}-helm-module 
    {{- end }}
      volumes:
      - name: nginx-volume
        configMap:
          name: {{ include "mychart.name" . }}
          items:
          - key: index.html
            path: index.html
      containers:
        - name: testchart
          image: "nginx:1.16.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
          - name:  nginx-volume
            mountPath: /usr/share/nginx/html
